/*
authentik

Making authentication simple.

API version: 2026.5.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the AccountLockdownFlowResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountLockdownFlowResponse{}

// AccountLockdownFlowResponse struct for AccountLockdownFlowResponse
type AccountLockdownFlowResponse struct {
	// URL to redirect to for lockdown flow
	FlowUrl              string `json:"flow_url"`
	AdditionalProperties map[string]interface{}
}

type _AccountLockdownFlowResponse AccountLockdownFlowResponse

// NewAccountLockdownFlowResponse instantiates a new AccountLockdownFlowResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountLockdownFlowResponse(flowUrl string) *AccountLockdownFlowResponse {
	this := AccountLockdownFlowResponse{}
	this.FlowUrl = flowUrl
	return &this
}

// NewAccountLockdownFlowResponseWithDefaults instantiates a new AccountLockdownFlowResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountLockdownFlowResponseWithDefaults() *AccountLockdownFlowResponse {
	this := AccountLockdownFlowResponse{}
	return &this
}

// GetFlowUrl returns the FlowUrl field value
func (o *AccountLockdownFlowResponse) GetFlowUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FlowUrl
}

// GetFlowUrlOk returns a tuple with the FlowUrl field value
// and a boolean to check if the value has been set.
func (o *AccountLockdownFlowResponse) GetFlowUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FlowUrl, true
}

// SetFlowUrl sets field value
func (o *AccountLockdownFlowResponse) SetFlowUrl(v string) {
	o.FlowUrl = v
}

func (o AccountLockdownFlowResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountLockdownFlowResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["flow_url"] = o.FlowUrl

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AccountLockdownFlowResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"flow_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccountLockdownFlowResponse := _AccountLockdownFlowResponse{}

	err = json.Unmarshal(data, &varAccountLockdownFlowResponse)

	if err != nil {
		return err
	}

	*o = AccountLockdownFlowResponse(varAccountLockdownFlowResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "flow_url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAccountLockdownFlowResponse struct {
	value *AccountLockdownFlowResponse
	isSet bool
}

func (v NullableAccountLockdownFlowResponse) Get() *AccountLockdownFlowResponse {
	return v.value
}

func (v *NullableAccountLockdownFlowResponse) Set(val *AccountLockdownFlowResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountLockdownFlowResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountLockdownFlowResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountLockdownFlowResponse(val *AccountLockdownFlowResponse) *NullableAccountLockdownFlowResponse {
	return &NullableAccountLockdownFlowResponse{value: val, isSet: true}
}

func (v NullableAccountLockdownFlowResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountLockdownFlowResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
