/*
authentik

Making authentication simple.

API version: 2026.5.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the PatchedAccountLockdownStageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedAccountLockdownStageRequest{}

// PatchedAccountLockdownStageRequest AccountLockdownStage Serializer
type PatchedAccountLockdownStageRequest struct {
	Name *string `json:"name,omitempty"`
	// Deactivate the user account (set is_active to False)
	DeactivateUser *bool `json:"deactivate_user,omitempty"`
	// Set an unusable password for the user
	SetUnusablePassword *bool `json:"set_unusable_password,omitempty"`
	// Delete all active sessions for the user
	DeleteSessions *bool `json:"delete_sessions,omitempty"`
	// Revoke all tokens for the user (API, app password, recovery, verification, OAuth2)
	RevokeTokens *bool `json:"revoke_tokens,omitempty"`
	// Title shown to users after self-service lockdown
	SelfServiceMessageTitle *string `json:"self_service_message_title,omitempty"`
	// HTML message shown to users after self-service lockdown. Supports HTML formatting.
	SelfServiceMessage *string `json:"self_service_message,omitempty"`
	// Flow to redirect users to after self-service lockdown. This flow should not require authentication since the user's session is deleted.
	SelfServiceCompletionFlow NullableString `json:"self_service_completion_flow,omitempty"`
	AdditionalProperties      map[string]interface{}
}

type _PatchedAccountLockdownStageRequest PatchedAccountLockdownStageRequest

// NewPatchedAccountLockdownStageRequest instantiates a new PatchedAccountLockdownStageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedAccountLockdownStageRequest() *PatchedAccountLockdownStageRequest {
	this := PatchedAccountLockdownStageRequest{}
	return &this
}

// NewPatchedAccountLockdownStageRequestWithDefaults instantiates a new PatchedAccountLockdownStageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedAccountLockdownStageRequestWithDefaults() *PatchedAccountLockdownStageRequest {
	this := PatchedAccountLockdownStageRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PatchedAccountLockdownStageRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedAccountLockdownStageRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PatchedAccountLockdownStageRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PatchedAccountLockdownStageRequest) SetName(v string) {
	o.Name = &v
}

// GetDeactivateUser returns the DeactivateUser field value if set, zero value otherwise.
func (o *PatchedAccountLockdownStageRequest) GetDeactivateUser() bool {
	if o == nil || IsNil(o.DeactivateUser) {
		var ret bool
		return ret
	}
	return *o.DeactivateUser
}

// GetDeactivateUserOk returns a tuple with the DeactivateUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedAccountLockdownStageRequest) GetDeactivateUserOk() (*bool, bool) {
	if o == nil || IsNil(o.DeactivateUser) {
		return nil, false
	}
	return o.DeactivateUser, true
}

// HasDeactivateUser returns a boolean if a field has been set.
func (o *PatchedAccountLockdownStageRequest) HasDeactivateUser() bool {
	if o != nil && !IsNil(o.DeactivateUser) {
		return true
	}

	return false
}

// SetDeactivateUser gets a reference to the given bool and assigns it to the DeactivateUser field.
func (o *PatchedAccountLockdownStageRequest) SetDeactivateUser(v bool) {
	o.DeactivateUser = &v
}

// GetSetUnusablePassword returns the SetUnusablePassword field value if set, zero value otherwise.
func (o *PatchedAccountLockdownStageRequest) GetSetUnusablePassword() bool {
	if o == nil || IsNil(o.SetUnusablePassword) {
		var ret bool
		return ret
	}
	return *o.SetUnusablePassword
}

// GetSetUnusablePasswordOk returns a tuple with the SetUnusablePassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedAccountLockdownStageRequest) GetSetUnusablePasswordOk() (*bool, bool) {
	if o == nil || IsNil(o.SetUnusablePassword) {
		return nil, false
	}
	return o.SetUnusablePassword, true
}

// HasSetUnusablePassword returns a boolean if a field has been set.
func (o *PatchedAccountLockdownStageRequest) HasSetUnusablePassword() bool {
	if o != nil && !IsNil(o.SetUnusablePassword) {
		return true
	}

	return false
}

// SetSetUnusablePassword gets a reference to the given bool and assigns it to the SetUnusablePassword field.
func (o *PatchedAccountLockdownStageRequest) SetSetUnusablePassword(v bool) {
	o.SetUnusablePassword = &v
}

// GetDeleteSessions returns the DeleteSessions field value if set, zero value otherwise.
func (o *PatchedAccountLockdownStageRequest) GetDeleteSessions() bool {
	if o == nil || IsNil(o.DeleteSessions) {
		var ret bool
		return ret
	}
	return *o.DeleteSessions
}

// GetDeleteSessionsOk returns a tuple with the DeleteSessions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedAccountLockdownStageRequest) GetDeleteSessionsOk() (*bool, bool) {
	if o == nil || IsNil(o.DeleteSessions) {
		return nil, false
	}
	return o.DeleteSessions, true
}

// HasDeleteSessions returns a boolean if a field has been set.
func (o *PatchedAccountLockdownStageRequest) HasDeleteSessions() bool {
	if o != nil && !IsNil(o.DeleteSessions) {
		return true
	}

	return false
}

// SetDeleteSessions gets a reference to the given bool and assigns it to the DeleteSessions field.
func (o *PatchedAccountLockdownStageRequest) SetDeleteSessions(v bool) {
	o.DeleteSessions = &v
}

// GetRevokeTokens returns the RevokeTokens field value if set, zero value otherwise.
func (o *PatchedAccountLockdownStageRequest) GetRevokeTokens() bool {
	if o == nil || IsNil(o.RevokeTokens) {
		var ret bool
		return ret
	}
	return *o.RevokeTokens
}

// GetRevokeTokensOk returns a tuple with the RevokeTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedAccountLockdownStageRequest) GetRevokeTokensOk() (*bool, bool) {
	if o == nil || IsNil(o.RevokeTokens) {
		return nil, false
	}
	return o.RevokeTokens, true
}

// HasRevokeTokens returns a boolean if a field has been set.
func (o *PatchedAccountLockdownStageRequest) HasRevokeTokens() bool {
	if o != nil && !IsNil(o.RevokeTokens) {
		return true
	}

	return false
}

// SetRevokeTokens gets a reference to the given bool and assigns it to the RevokeTokens field.
func (o *PatchedAccountLockdownStageRequest) SetRevokeTokens(v bool) {
	o.RevokeTokens = &v
}

// GetSelfServiceMessageTitle returns the SelfServiceMessageTitle field value if set, zero value otherwise.
func (o *PatchedAccountLockdownStageRequest) GetSelfServiceMessageTitle() string {
	if o == nil || IsNil(o.SelfServiceMessageTitle) {
		var ret string
		return ret
	}
	return *o.SelfServiceMessageTitle
}

// GetSelfServiceMessageTitleOk returns a tuple with the SelfServiceMessageTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedAccountLockdownStageRequest) GetSelfServiceMessageTitleOk() (*string, bool) {
	if o == nil || IsNil(o.SelfServiceMessageTitle) {
		return nil, false
	}
	return o.SelfServiceMessageTitle, true
}

// HasSelfServiceMessageTitle returns a boolean if a field has been set.
func (o *PatchedAccountLockdownStageRequest) HasSelfServiceMessageTitle() bool {
	if o != nil && !IsNil(o.SelfServiceMessageTitle) {
		return true
	}

	return false
}

// SetSelfServiceMessageTitle gets a reference to the given string and assigns it to the SelfServiceMessageTitle field.
func (o *PatchedAccountLockdownStageRequest) SetSelfServiceMessageTitle(v string) {
	o.SelfServiceMessageTitle = &v
}

// GetSelfServiceMessage returns the SelfServiceMessage field value if set, zero value otherwise.
func (o *PatchedAccountLockdownStageRequest) GetSelfServiceMessage() string {
	if o == nil || IsNil(o.SelfServiceMessage) {
		var ret string
		return ret
	}
	return *o.SelfServiceMessage
}

// GetSelfServiceMessageOk returns a tuple with the SelfServiceMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedAccountLockdownStageRequest) GetSelfServiceMessageOk() (*string, bool) {
	if o == nil || IsNil(o.SelfServiceMessage) {
		return nil, false
	}
	return o.SelfServiceMessage, true
}

// HasSelfServiceMessage returns a boolean if a field has been set.
func (o *PatchedAccountLockdownStageRequest) HasSelfServiceMessage() bool {
	if o != nil && !IsNil(o.SelfServiceMessage) {
		return true
	}

	return false
}

// SetSelfServiceMessage gets a reference to the given string and assigns it to the SelfServiceMessage field.
func (o *PatchedAccountLockdownStageRequest) SetSelfServiceMessage(v string) {
	o.SelfServiceMessage = &v
}

// GetSelfServiceCompletionFlow returns the SelfServiceCompletionFlow field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedAccountLockdownStageRequest) GetSelfServiceCompletionFlow() string {
	if o == nil || IsNil(o.SelfServiceCompletionFlow.Get()) {
		var ret string
		return ret
	}
	return *o.SelfServiceCompletionFlow.Get()
}

// GetSelfServiceCompletionFlowOk returns a tuple with the SelfServiceCompletionFlow field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedAccountLockdownStageRequest) GetSelfServiceCompletionFlowOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SelfServiceCompletionFlow.Get(), o.SelfServiceCompletionFlow.IsSet()
}

// HasSelfServiceCompletionFlow returns a boolean if a field has been set.
func (o *PatchedAccountLockdownStageRequest) HasSelfServiceCompletionFlow() bool {
	if o != nil && o.SelfServiceCompletionFlow.IsSet() {
		return true
	}

	return false
}

// SetSelfServiceCompletionFlow gets a reference to the given NullableString and assigns it to the SelfServiceCompletionFlow field.
func (o *PatchedAccountLockdownStageRequest) SetSelfServiceCompletionFlow(v string) {
	o.SelfServiceCompletionFlow.Set(&v)
}

// SetSelfServiceCompletionFlowNil sets the value for SelfServiceCompletionFlow to be an explicit nil
func (o *PatchedAccountLockdownStageRequest) SetSelfServiceCompletionFlowNil() {
	o.SelfServiceCompletionFlow.Set(nil)
}

// UnsetSelfServiceCompletionFlow ensures that no value is present for SelfServiceCompletionFlow, not even an explicit nil
func (o *PatchedAccountLockdownStageRequest) UnsetSelfServiceCompletionFlow() {
	o.SelfServiceCompletionFlow.Unset()
}

func (o PatchedAccountLockdownStageRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedAccountLockdownStageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.DeactivateUser) {
		toSerialize["deactivate_user"] = o.DeactivateUser
	}
	if !IsNil(o.SetUnusablePassword) {
		toSerialize["set_unusable_password"] = o.SetUnusablePassword
	}
	if !IsNil(o.DeleteSessions) {
		toSerialize["delete_sessions"] = o.DeleteSessions
	}
	if !IsNil(o.RevokeTokens) {
		toSerialize["revoke_tokens"] = o.RevokeTokens
	}
	if !IsNil(o.SelfServiceMessageTitle) {
		toSerialize["self_service_message_title"] = o.SelfServiceMessageTitle
	}
	if !IsNil(o.SelfServiceMessage) {
		toSerialize["self_service_message"] = o.SelfServiceMessage
	}
	if o.SelfServiceCompletionFlow.IsSet() {
		toSerialize["self_service_completion_flow"] = o.SelfServiceCompletionFlow.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PatchedAccountLockdownStageRequest) UnmarshalJSON(data []byte) (err error) {
	varPatchedAccountLockdownStageRequest := _PatchedAccountLockdownStageRequest{}

	err = json.Unmarshal(data, &varPatchedAccountLockdownStageRequest)

	if err != nil {
		return err
	}

	*o = PatchedAccountLockdownStageRequest(varPatchedAccountLockdownStageRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "deactivate_user")
		delete(additionalProperties, "set_unusable_password")
		delete(additionalProperties, "delete_sessions")
		delete(additionalProperties, "revoke_tokens")
		delete(additionalProperties, "self_service_message_title")
		delete(additionalProperties, "self_service_message")
		delete(additionalProperties, "self_service_completion_flow")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePatchedAccountLockdownStageRequest struct {
	value *PatchedAccountLockdownStageRequest
	isSet bool
}

func (v NullablePatchedAccountLockdownStageRequest) Get() *PatchedAccountLockdownStageRequest {
	return v.value
}

func (v *NullablePatchedAccountLockdownStageRequest) Set(val *PatchedAccountLockdownStageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedAccountLockdownStageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedAccountLockdownStageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedAccountLockdownStageRequest(val *PatchedAccountLockdownStageRequest) *NullablePatchedAccountLockdownStageRequest {
	return &NullablePatchedAccountLockdownStageRequest{value: val, isSet: true}
}

func (v NullablePatchedAccountLockdownStageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedAccountLockdownStageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
