/*
authentik

Making authentication simple.

API version: 2026.5.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the ObjectAttributeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ObjectAttributeRequest{}

// ObjectAttributeRequest struct for ObjectAttributeRequest
type ObjectAttributeRequest struct {
	ObjectType           string                  `json:"object_type"`
	Enabled              *bool                   `json:"enabled,omitempty"`
	Key                  string                  `json:"key"`
	Label                string                  `json:"label"`
	Regex                *string                 `json:"regex,omitempty"`
	Type                 ObjectAttributeTypeEnum `json:"type"`
	Group                *string                 `json:"group,omitempty"`
	FlagUnique           *bool                   `json:"flag_unique,omitempty"`
	FlagRequired         *bool                   `json:"flag_required,omitempty"`
	IsArray              *bool                   `json:"is_array,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ObjectAttributeRequest ObjectAttributeRequest

// NewObjectAttributeRequest instantiates a new ObjectAttributeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObjectAttributeRequest(objectType string, key string, label string, type_ ObjectAttributeTypeEnum) *ObjectAttributeRequest {
	this := ObjectAttributeRequest{}
	this.ObjectType = objectType
	this.Key = key
	this.Label = label
	this.Type = type_
	return &this
}

// NewObjectAttributeRequestWithDefaults instantiates a new ObjectAttributeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObjectAttributeRequestWithDefaults() *ObjectAttributeRequest {
	this := ObjectAttributeRequest{}
	return &this
}

// GetObjectType returns the ObjectType field value
func (o *ObjectAttributeRequest) GetObjectType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value
// and a boolean to check if the value has been set.
func (o *ObjectAttributeRequest) GetObjectTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectType, true
}

// SetObjectType sets field value
func (o *ObjectAttributeRequest) SetObjectType(v string) {
	o.ObjectType = v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *ObjectAttributeRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectAttributeRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *ObjectAttributeRequest) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *ObjectAttributeRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetKey returns the Key field value
func (o *ObjectAttributeRequest) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *ObjectAttributeRequest) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *ObjectAttributeRequest) SetKey(v string) {
	o.Key = v
}

// GetLabel returns the Label field value
func (o *ObjectAttributeRequest) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *ObjectAttributeRequest) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *ObjectAttributeRequest) SetLabel(v string) {
	o.Label = v
}

// GetRegex returns the Regex field value if set, zero value otherwise.
func (o *ObjectAttributeRequest) GetRegex() string {
	if o == nil || IsNil(o.Regex) {
		var ret string
		return ret
	}
	return *o.Regex
}

// GetRegexOk returns a tuple with the Regex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectAttributeRequest) GetRegexOk() (*string, bool) {
	if o == nil || IsNil(o.Regex) {
		return nil, false
	}
	return o.Regex, true
}

// HasRegex returns a boolean if a field has been set.
func (o *ObjectAttributeRequest) HasRegex() bool {
	if o != nil && !IsNil(o.Regex) {
		return true
	}

	return false
}

// SetRegex gets a reference to the given string and assigns it to the Regex field.
func (o *ObjectAttributeRequest) SetRegex(v string) {
	o.Regex = &v
}

// GetType returns the Type field value
func (o *ObjectAttributeRequest) GetType() ObjectAttributeTypeEnum {
	if o == nil {
		var ret ObjectAttributeTypeEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ObjectAttributeRequest) GetTypeOk() (*ObjectAttributeTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ObjectAttributeRequest) SetType(v ObjectAttributeTypeEnum) {
	o.Type = v
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *ObjectAttributeRequest) GetGroup() string {
	if o == nil || IsNil(o.Group) {
		var ret string
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectAttributeRequest) GetGroupOk() (*string, bool) {
	if o == nil || IsNil(o.Group) {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *ObjectAttributeRequest) HasGroup() bool {
	if o != nil && !IsNil(o.Group) {
		return true
	}

	return false
}

// SetGroup gets a reference to the given string and assigns it to the Group field.
func (o *ObjectAttributeRequest) SetGroup(v string) {
	o.Group = &v
}

// GetFlagUnique returns the FlagUnique field value if set, zero value otherwise.
func (o *ObjectAttributeRequest) GetFlagUnique() bool {
	if o == nil || IsNil(o.FlagUnique) {
		var ret bool
		return ret
	}
	return *o.FlagUnique
}

// GetFlagUniqueOk returns a tuple with the FlagUnique field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectAttributeRequest) GetFlagUniqueOk() (*bool, bool) {
	if o == nil || IsNil(o.FlagUnique) {
		return nil, false
	}
	return o.FlagUnique, true
}

// HasFlagUnique returns a boolean if a field has been set.
func (o *ObjectAttributeRequest) HasFlagUnique() bool {
	if o != nil && !IsNil(o.FlagUnique) {
		return true
	}

	return false
}

// SetFlagUnique gets a reference to the given bool and assigns it to the FlagUnique field.
func (o *ObjectAttributeRequest) SetFlagUnique(v bool) {
	o.FlagUnique = &v
}

// GetFlagRequired returns the FlagRequired field value if set, zero value otherwise.
func (o *ObjectAttributeRequest) GetFlagRequired() bool {
	if o == nil || IsNil(o.FlagRequired) {
		var ret bool
		return ret
	}
	return *o.FlagRequired
}

// GetFlagRequiredOk returns a tuple with the FlagRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectAttributeRequest) GetFlagRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.FlagRequired) {
		return nil, false
	}
	return o.FlagRequired, true
}

// HasFlagRequired returns a boolean if a field has been set.
func (o *ObjectAttributeRequest) HasFlagRequired() bool {
	if o != nil && !IsNil(o.FlagRequired) {
		return true
	}

	return false
}

// SetFlagRequired gets a reference to the given bool and assigns it to the FlagRequired field.
func (o *ObjectAttributeRequest) SetFlagRequired(v bool) {
	o.FlagRequired = &v
}

// GetIsArray returns the IsArray field value if set, zero value otherwise.
func (o *ObjectAttributeRequest) GetIsArray() bool {
	if o == nil || IsNil(o.IsArray) {
		var ret bool
		return ret
	}
	return *o.IsArray
}

// GetIsArrayOk returns a tuple with the IsArray field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectAttributeRequest) GetIsArrayOk() (*bool, bool) {
	if o == nil || IsNil(o.IsArray) {
		return nil, false
	}
	return o.IsArray, true
}

// HasIsArray returns a boolean if a field has been set.
func (o *ObjectAttributeRequest) HasIsArray() bool {
	if o != nil && !IsNil(o.IsArray) {
		return true
	}

	return false
}

// SetIsArray gets a reference to the given bool and assigns it to the IsArray field.
func (o *ObjectAttributeRequest) SetIsArray(v bool) {
	o.IsArray = &v
}

func (o ObjectAttributeRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ObjectAttributeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["object_type"] = o.ObjectType
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	toSerialize["key"] = o.Key
	toSerialize["label"] = o.Label
	if !IsNil(o.Regex) {
		toSerialize["regex"] = o.Regex
	}
	toSerialize["type"] = o.Type
	if !IsNil(o.Group) {
		toSerialize["group"] = o.Group
	}
	if !IsNil(o.FlagUnique) {
		toSerialize["flag_unique"] = o.FlagUnique
	}
	if !IsNil(o.FlagRequired) {
		toSerialize["flag_required"] = o.FlagRequired
	}
	if !IsNil(o.IsArray) {
		toSerialize["is_array"] = o.IsArray
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ObjectAttributeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"object_type",
		"key",
		"label",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varObjectAttributeRequest := _ObjectAttributeRequest{}

	err = json.Unmarshal(data, &varObjectAttributeRequest)

	if err != nil {
		return err
	}

	*o = ObjectAttributeRequest(varObjectAttributeRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "object_type")
		delete(additionalProperties, "enabled")
		delete(additionalProperties, "key")
		delete(additionalProperties, "label")
		delete(additionalProperties, "regex")
		delete(additionalProperties, "type")
		delete(additionalProperties, "group")
		delete(additionalProperties, "flag_unique")
		delete(additionalProperties, "flag_required")
		delete(additionalProperties, "is_array")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableObjectAttributeRequest struct {
	value *ObjectAttributeRequest
	isSet bool
}

func (v NullableObjectAttributeRequest) Get() *ObjectAttributeRequest {
	return v.value
}

func (v *NullableObjectAttributeRequest) Set(val *ObjectAttributeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableObjectAttributeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableObjectAttributeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObjectAttributeRequest(val *ObjectAttributeRequest) *NullableObjectAttributeRequest {
	return &NullableObjectAttributeRequest{value: val, isSet: true}
}

func (v NullableObjectAttributeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObjectAttributeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
