/*
authentik

Making authentication simple.

API version: 2026.5.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the ObjectAttribute type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ObjectAttribute{}

// ObjectAttribute struct for ObjectAttribute
type ObjectAttribute struct {
	AttributeId *string     `json:"attribute_id,omitempty"`
	ContentType ContentType `json:"content_type"`
	Created     time.Time   `json:"created"`
	LastUpdated time.Time   `json:"last_updated"`
	// Objects that are managed by authentik. These objects are created and updated automatically. This flag only indicates that an object can be overwritten by migrations. You can still modify the objects via the API, but expect changes to be overwritten in a later update.
	Managed              NullableString          `json:"managed,omitempty"`
	Label                string                  `json:"label"`
	Key                  string                  `json:"key"`
	Type                 ObjectAttributeTypeEnum `json:"type"`
	FlagUnique           *bool                   `json:"flag_unique,omitempty"`
	FlagRequired         *bool                   `json:"flag_required,omitempty"`
	Regex                string                  `json:"regex"`
	IsArray              *bool                   `json:"is_array,omitempty"`
	ObjectType           int32                   `json:"object_type"`
	AdditionalProperties map[string]interface{}
}

type _ObjectAttribute ObjectAttribute

// NewObjectAttribute instantiates a new ObjectAttribute object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObjectAttribute(contentType ContentType, created time.Time, lastUpdated time.Time, label string, key string, type_ ObjectAttributeTypeEnum, regex string, objectType int32) *ObjectAttribute {
	this := ObjectAttribute{}
	this.ContentType = contentType
	this.Created = created
	this.LastUpdated = lastUpdated
	this.Label = label
	this.Key = key
	this.Type = type_
	this.Regex = regex
	this.ObjectType = objectType
	return &this
}

// NewObjectAttributeWithDefaults instantiates a new ObjectAttribute object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObjectAttributeWithDefaults() *ObjectAttribute {
	this := ObjectAttribute{}
	return &this
}

// GetAttributeId returns the AttributeId field value if set, zero value otherwise.
func (o *ObjectAttribute) GetAttributeId() string {
	if o == nil || IsNil(o.AttributeId) {
		var ret string
		return ret
	}
	return *o.AttributeId
}

// GetAttributeIdOk returns a tuple with the AttributeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectAttribute) GetAttributeIdOk() (*string, bool) {
	if o == nil || IsNil(o.AttributeId) {
		return nil, false
	}
	return o.AttributeId, true
}

// HasAttributeId returns a boolean if a field has been set.
func (o *ObjectAttribute) HasAttributeId() bool {
	if o != nil && !IsNil(o.AttributeId) {
		return true
	}

	return false
}

// SetAttributeId gets a reference to the given string and assigns it to the AttributeId field.
func (o *ObjectAttribute) SetAttributeId(v string) {
	o.AttributeId = &v
}

// GetContentType returns the ContentType field value
func (o *ObjectAttribute) GetContentType() ContentType {
	if o == nil {
		var ret ContentType
		return ret
	}

	return o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value
// and a boolean to check if the value has been set.
func (o *ObjectAttribute) GetContentTypeOk() (*ContentType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentType, true
}

// SetContentType sets field value
func (o *ObjectAttribute) SetContentType(v ContentType) {
	o.ContentType = v
}

// GetCreated returns the Created field value
func (o *ObjectAttribute) GetCreated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *ObjectAttribute) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *ObjectAttribute) SetCreated(v time.Time) {
	o.Created = v
}

// GetLastUpdated returns the LastUpdated field value
func (o *ObjectAttribute) GetLastUpdated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastUpdated
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value
// and a boolean to check if the value has been set.
func (o *ObjectAttribute) GetLastUpdatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastUpdated, true
}

// SetLastUpdated sets field value
func (o *ObjectAttribute) SetLastUpdated(v time.Time) {
	o.LastUpdated = v
}

// GetManaged returns the Managed field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ObjectAttribute) GetManaged() string {
	if o == nil || IsNil(o.Managed.Get()) {
		var ret string
		return ret
	}
	return *o.Managed.Get()
}

// GetManagedOk returns a tuple with the Managed field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ObjectAttribute) GetManagedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Managed.Get(), o.Managed.IsSet()
}

// HasManaged returns a boolean if a field has been set.
func (o *ObjectAttribute) HasManaged() bool {
	if o != nil && o.Managed.IsSet() {
		return true
	}

	return false
}

// SetManaged gets a reference to the given NullableString and assigns it to the Managed field.
func (o *ObjectAttribute) SetManaged(v string) {
	o.Managed.Set(&v)
}

// SetManagedNil sets the value for Managed to be an explicit nil
func (o *ObjectAttribute) SetManagedNil() {
	o.Managed.Set(nil)
}

// UnsetManaged ensures that no value is present for Managed, not even an explicit nil
func (o *ObjectAttribute) UnsetManaged() {
	o.Managed.Unset()
}

// GetLabel returns the Label field value
func (o *ObjectAttribute) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *ObjectAttribute) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *ObjectAttribute) SetLabel(v string) {
	o.Label = v
}

// GetKey returns the Key field value
func (o *ObjectAttribute) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *ObjectAttribute) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *ObjectAttribute) SetKey(v string) {
	o.Key = v
}

// GetType returns the Type field value
func (o *ObjectAttribute) GetType() ObjectAttributeTypeEnum {
	if o == nil {
		var ret ObjectAttributeTypeEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ObjectAttribute) GetTypeOk() (*ObjectAttributeTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ObjectAttribute) SetType(v ObjectAttributeTypeEnum) {
	o.Type = v
}

// GetFlagUnique returns the FlagUnique field value if set, zero value otherwise.
func (o *ObjectAttribute) GetFlagUnique() bool {
	if o == nil || IsNil(o.FlagUnique) {
		var ret bool
		return ret
	}
	return *o.FlagUnique
}

// GetFlagUniqueOk returns a tuple with the FlagUnique field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectAttribute) GetFlagUniqueOk() (*bool, bool) {
	if o == nil || IsNil(o.FlagUnique) {
		return nil, false
	}
	return o.FlagUnique, true
}

// HasFlagUnique returns a boolean if a field has been set.
func (o *ObjectAttribute) HasFlagUnique() bool {
	if o != nil && !IsNil(o.FlagUnique) {
		return true
	}

	return false
}

// SetFlagUnique gets a reference to the given bool and assigns it to the FlagUnique field.
func (o *ObjectAttribute) SetFlagUnique(v bool) {
	o.FlagUnique = &v
}

// GetFlagRequired returns the FlagRequired field value if set, zero value otherwise.
func (o *ObjectAttribute) GetFlagRequired() bool {
	if o == nil || IsNil(o.FlagRequired) {
		var ret bool
		return ret
	}
	return *o.FlagRequired
}

// GetFlagRequiredOk returns a tuple with the FlagRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectAttribute) GetFlagRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.FlagRequired) {
		return nil, false
	}
	return o.FlagRequired, true
}

// HasFlagRequired returns a boolean if a field has been set.
func (o *ObjectAttribute) HasFlagRequired() bool {
	if o != nil && !IsNil(o.FlagRequired) {
		return true
	}

	return false
}

// SetFlagRequired gets a reference to the given bool and assigns it to the FlagRequired field.
func (o *ObjectAttribute) SetFlagRequired(v bool) {
	o.FlagRequired = &v
}

// GetRegex returns the Regex field value
func (o *ObjectAttribute) GetRegex() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Regex
}

// GetRegexOk returns a tuple with the Regex field value
// and a boolean to check if the value has been set.
func (o *ObjectAttribute) GetRegexOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Regex, true
}

// SetRegex sets field value
func (o *ObjectAttribute) SetRegex(v string) {
	o.Regex = v
}

// GetIsArray returns the IsArray field value if set, zero value otherwise.
func (o *ObjectAttribute) GetIsArray() bool {
	if o == nil || IsNil(o.IsArray) {
		var ret bool
		return ret
	}
	return *o.IsArray
}

// GetIsArrayOk returns a tuple with the IsArray field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectAttribute) GetIsArrayOk() (*bool, bool) {
	if o == nil || IsNil(o.IsArray) {
		return nil, false
	}
	return o.IsArray, true
}

// HasIsArray returns a boolean if a field has been set.
func (o *ObjectAttribute) HasIsArray() bool {
	if o != nil && !IsNil(o.IsArray) {
		return true
	}

	return false
}

// SetIsArray gets a reference to the given bool and assigns it to the IsArray field.
func (o *ObjectAttribute) SetIsArray(v bool) {
	o.IsArray = &v
}

// GetObjectType returns the ObjectType field value
func (o *ObjectAttribute) GetObjectType() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value
// and a boolean to check if the value has been set.
func (o *ObjectAttribute) GetObjectTypeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectType, true
}

// SetObjectType sets field value
func (o *ObjectAttribute) SetObjectType(v int32) {
	o.ObjectType = v
}

func (o ObjectAttribute) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ObjectAttribute) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AttributeId) {
		toSerialize["attribute_id"] = o.AttributeId
	}
	toSerialize["content_type"] = o.ContentType
	toSerialize["created"] = o.Created
	toSerialize["last_updated"] = o.LastUpdated
	if o.Managed.IsSet() {
		toSerialize["managed"] = o.Managed.Get()
	}
	toSerialize["label"] = o.Label
	toSerialize["key"] = o.Key
	toSerialize["type"] = o.Type
	if !IsNil(o.FlagUnique) {
		toSerialize["flag_unique"] = o.FlagUnique
	}
	if !IsNil(o.FlagRequired) {
		toSerialize["flag_required"] = o.FlagRequired
	}
	toSerialize["regex"] = o.Regex
	if !IsNil(o.IsArray) {
		toSerialize["is_array"] = o.IsArray
	}
	toSerialize["object_type"] = o.ObjectType

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ObjectAttribute) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"content_type",
		"created",
		"last_updated",
		"label",
		"key",
		"type",
		"regex",
		"object_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varObjectAttribute := _ObjectAttribute{}

	err = json.Unmarshal(data, &varObjectAttribute)

	if err != nil {
		return err
	}

	*o = ObjectAttribute(varObjectAttribute)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "attribute_id")
		delete(additionalProperties, "content_type")
		delete(additionalProperties, "created")
		delete(additionalProperties, "last_updated")
		delete(additionalProperties, "managed")
		delete(additionalProperties, "label")
		delete(additionalProperties, "key")
		delete(additionalProperties, "type")
		delete(additionalProperties, "flag_unique")
		delete(additionalProperties, "flag_required")
		delete(additionalProperties, "regex")
		delete(additionalProperties, "is_array")
		delete(additionalProperties, "object_type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableObjectAttribute struct {
	value *ObjectAttribute
	isSet bool
}

func (v NullableObjectAttribute) Get() *ObjectAttribute {
	return v.value
}

func (v *NullableObjectAttribute) Set(val *ObjectAttribute) {
	v.value = val
	v.isSet = true
}

func (v NullableObjectAttribute) IsSet() bool {
	return v.isSet
}

func (v *NullableObjectAttribute) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObjectAttribute(val *ObjectAttribute) *NullableObjectAttribute {
	return &NullableObjectAttribute{value: val, isSet: true}
}

func (v NullableObjectAttribute) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObjectAttribute) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
