/*
authentik

Making authentication simple.

API version: 2026.5.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the DynamicURL type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DynamicURL{}

// DynamicURL Dynamic URL variants keyed by variant name. Includes a fallback URL.
type DynamicURL struct {
	Fallback             NullableString `json:"fallback,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DynamicURL DynamicURL

// NewDynamicURL instantiates a new DynamicURL object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDynamicURL() *DynamicURL {
	this := DynamicURL{}
	return &this
}

// NewDynamicURLWithDefaults instantiates a new DynamicURL object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDynamicURLWithDefaults() *DynamicURL {
	this := DynamicURL{}
	return &this
}

// GetFallback returns the Fallback field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DynamicURL) GetFallback() string {
	if o == nil || IsNil(o.Fallback.Get()) {
		var ret string
		return ret
	}
	return *o.Fallback.Get()
}

// GetFallbackOk returns a tuple with the Fallback field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DynamicURL) GetFallbackOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Fallback.Get(), o.Fallback.IsSet()
}

// HasFallback returns a boolean if a field has been set.
func (o *DynamicURL) HasFallback() bool {
	if o != nil && o.Fallback.IsSet() {
		return true
	}

	return false
}

// SetFallback gets a reference to the given NullableString and assigns it to the Fallback field.
func (o *DynamicURL) SetFallback(v string) {
	o.Fallback.Set(&v)
}

// SetFallbackNil sets the value for Fallback to be an explicit nil
func (o *DynamicURL) SetFallbackNil() {
	o.Fallback.Set(nil)
}

// UnsetFallback ensures that no value is present for Fallback, not even an explicit nil
func (o *DynamicURL) UnsetFallback() {
	o.Fallback.Unset()
}

func (o DynamicURL) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DynamicURL) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Fallback.IsSet() {
		toSerialize["fallback"] = o.Fallback.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DynamicURL) UnmarshalJSON(data []byte) (err error) {
	varDynamicURL := _DynamicURL{}

	err = json.Unmarshal(data, &varDynamicURL)

	if err != nil {
		return err
	}

	*o = DynamicURL(varDynamicURL)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "fallback")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDynamicURL struct {
	value *DynamicURL
	isSet bool
}

func (v NullableDynamicURL) Get() *DynamicURL {
	return v.value
}

func (v *NullableDynamicURL) Set(val *DynamicURL) {
	v.value = val
	v.isSet = true
}

func (v NullableDynamicURL) IsSet() bool {
	return v.isSet
}

func (v *NullableDynamicURL) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDynamicURL(val *DynamicURL) *NullableDynamicURL {
	return &NullableDynamicURL{value: val, isSet: true}
}

func (v NullableDynamicURL) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDynamicURL) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
