/*
authentik

Making authentication simple.

API version: 2026.5.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the ObjectAttributeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ObjectAttributeRequest{}

// ObjectAttributeRequest struct for ObjectAttributeRequest
type ObjectAttributeRequest struct {
	AttributeId *string `json:"attribute_id,omitempty"`
	// Objects that are managed by authentik. These objects are created and updated automatically. This flag only indicates that an object can be overwritten by migrations. You can still modify the objects via the API, but expect changes to be overwritten in a later update.
	Managed              NullableString          `json:"managed,omitempty"`
	Label                string                  `json:"label"`
	Key                  string                  `json:"key"`
	Type                 ObjectAttributeTypeEnum `json:"type"`
	FlagUnique           *bool                   `json:"flag_unique,omitempty"`
	FlagRequired         *bool                   `json:"flag_required,omitempty"`
	Regex                string                  `json:"regex"`
	IsArray              *bool                   `json:"is_array,omitempty"`
	ObjectType           int32                   `json:"object_type"`
	AdditionalProperties map[string]interface{}
}

type _ObjectAttributeRequest ObjectAttributeRequest

// NewObjectAttributeRequest instantiates a new ObjectAttributeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObjectAttributeRequest(label string, key string, type_ ObjectAttributeTypeEnum, regex string, objectType int32) *ObjectAttributeRequest {
	this := ObjectAttributeRequest{}
	this.Label = label
	this.Key = key
	this.Type = type_
	this.Regex = regex
	this.ObjectType = objectType
	return &this
}

// NewObjectAttributeRequestWithDefaults instantiates a new ObjectAttributeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObjectAttributeRequestWithDefaults() *ObjectAttributeRequest {
	this := ObjectAttributeRequest{}
	return &this
}

// GetAttributeId returns the AttributeId field value if set, zero value otherwise.
func (o *ObjectAttributeRequest) GetAttributeId() string {
	if o == nil || IsNil(o.AttributeId) {
		var ret string
		return ret
	}
	return *o.AttributeId
}

// GetAttributeIdOk returns a tuple with the AttributeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectAttributeRequest) GetAttributeIdOk() (*string, bool) {
	if o == nil || IsNil(o.AttributeId) {
		return nil, false
	}
	return o.AttributeId, true
}

// HasAttributeId returns a boolean if a field has been set.
func (o *ObjectAttributeRequest) HasAttributeId() bool {
	if o != nil && !IsNil(o.AttributeId) {
		return true
	}

	return false
}

// SetAttributeId gets a reference to the given string and assigns it to the AttributeId field.
func (o *ObjectAttributeRequest) SetAttributeId(v string) {
	o.AttributeId = &v
}

// GetManaged returns the Managed field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ObjectAttributeRequest) GetManaged() string {
	if o == nil || IsNil(o.Managed.Get()) {
		var ret string
		return ret
	}
	return *o.Managed.Get()
}

// GetManagedOk returns a tuple with the Managed field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ObjectAttributeRequest) GetManagedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Managed.Get(), o.Managed.IsSet()
}

// HasManaged returns a boolean if a field has been set.
func (o *ObjectAttributeRequest) HasManaged() bool {
	if o != nil && o.Managed.IsSet() {
		return true
	}

	return false
}

// SetManaged gets a reference to the given NullableString and assigns it to the Managed field.
func (o *ObjectAttributeRequest) SetManaged(v string) {
	o.Managed.Set(&v)
}

// SetManagedNil sets the value for Managed to be an explicit nil
func (o *ObjectAttributeRequest) SetManagedNil() {
	o.Managed.Set(nil)
}

// UnsetManaged ensures that no value is present for Managed, not even an explicit nil
func (o *ObjectAttributeRequest) UnsetManaged() {
	o.Managed.Unset()
}

// GetLabel returns the Label field value
func (o *ObjectAttributeRequest) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *ObjectAttributeRequest) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *ObjectAttributeRequest) SetLabel(v string) {
	o.Label = v
}

// GetKey returns the Key field value
func (o *ObjectAttributeRequest) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *ObjectAttributeRequest) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *ObjectAttributeRequest) SetKey(v string) {
	o.Key = v
}

// GetType returns the Type field value
func (o *ObjectAttributeRequest) GetType() ObjectAttributeTypeEnum {
	if o == nil {
		var ret ObjectAttributeTypeEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ObjectAttributeRequest) GetTypeOk() (*ObjectAttributeTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ObjectAttributeRequest) SetType(v ObjectAttributeTypeEnum) {
	o.Type = v
}

// GetFlagUnique returns the FlagUnique field value if set, zero value otherwise.
func (o *ObjectAttributeRequest) GetFlagUnique() bool {
	if o == nil || IsNil(o.FlagUnique) {
		var ret bool
		return ret
	}
	return *o.FlagUnique
}

// GetFlagUniqueOk returns a tuple with the FlagUnique field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectAttributeRequest) GetFlagUniqueOk() (*bool, bool) {
	if o == nil || IsNil(o.FlagUnique) {
		return nil, false
	}
	return o.FlagUnique, true
}

// HasFlagUnique returns a boolean if a field has been set.
func (o *ObjectAttributeRequest) HasFlagUnique() bool {
	if o != nil && !IsNil(o.FlagUnique) {
		return true
	}

	return false
}

// SetFlagUnique gets a reference to the given bool and assigns it to the FlagUnique field.
func (o *ObjectAttributeRequest) SetFlagUnique(v bool) {
	o.FlagUnique = &v
}

// GetFlagRequired returns the FlagRequired field value if set, zero value otherwise.
func (o *ObjectAttributeRequest) GetFlagRequired() bool {
	if o == nil || IsNil(o.FlagRequired) {
		var ret bool
		return ret
	}
	return *o.FlagRequired
}

// GetFlagRequiredOk returns a tuple with the FlagRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectAttributeRequest) GetFlagRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.FlagRequired) {
		return nil, false
	}
	return o.FlagRequired, true
}

// HasFlagRequired returns a boolean if a field has been set.
func (o *ObjectAttributeRequest) HasFlagRequired() bool {
	if o != nil && !IsNil(o.FlagRequired) {
		return true
	}

	return false
}

// SetFlagRequired gets a reference to the given bool and assigns it to the FlagRequired field.
func (o *ObjectAttributeRequest) SetFlagRequired(v bool) {
	o.FlagRequired = &v
}

// GetRegex returns the Regex field value
func (o *ObjectAttributeRequest) GetRegex() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Regex
}

// GetRegexOk returns a tuple with the Regex field value
// and a boolean to check if the value has been set.
func (o *ObjectAttributeRequest) GetRegexOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Regex, true
}

// SetRegex sets field value
func (o *ObjectAttributeRequest) SetRegex(v string) {
	o.Regex = v
}

// GetIsArray returns the IsArray field value if set, zero value otherwise.
func (o *ObjectAttributeRequest) GetIsArray() bool {
	if o == nil || IsNil(o.IsArray) {
		var ret bool
		return ret
	}
	return *o.IsArray
}

// GetIsArrayOk returns a tuple with the IsArray field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectAttributeRequest) GetIsArrayOk() (*bool, bool) {
	if o == nil || IsNil(o.IsArray) {
		return nil, false
	}
	return o.IsArray, true
}

// HasIsArray returns a boolean if a field has been set.
func (o *ObjectAttributeRequest) HasIsArray() bool {
	if o != nil && !IsNil(o.IsArray) {
		return true
	}

	return false
}

// SetIsArray gets a reference to the given bool and assigns it to the IsArray field.
func (o *ObjectAttributeRequest) SetIsArray(v bool) {
	o.IsArray = &v
}

// GetObjectType returns the ObjectType field value
func (o *ObjectAttributeRequest) GetObjectType() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value
// and a boolean to check if the value has been set.
func (o *ObjectAttributeRequest) GetObjectTypeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectType, true
}

// SetObjectType sets field value
func (o *ObjectAttributeRequest) SetObjectType(v int32) {
	o.ObjectType = v
}

func (o ObjectAttributeRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ObjectAttributeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AttributeId) {
		toSerialize["attribute_id"] = o.AttributeId
	}
	if o.Managed.IsSet() {
		toSerialize["managed"] = o.Managed.Get()
	}
	toSerialize["label"] = o.Label
	toSerialize["key"] = o.Key
	toSerialize["type"] = o.Type
	if !IsNil(o.FlagUnique) {
		toSerialize["flag_unique"] = o.FlagUnique
	}
	if !IsNil(o.FlagRequired) {
		toSerialize["flag_required"] = o.FlagRequired
	}
	toSerialize["regex"] = o.Regex
	if !IsNil(o.IsArray) {
		toSerialize["is_array"] = o.IsArray
	}
	toSerialize["object_type"] = o.ObjectType

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ObjectAttributeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"label",
		"key",
		"type",
		"regex",
		"object_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varObjectAttributeRequest := _ObjectAttributeRequest{}

	err = json.Unmarshal(data, &varObjectAttributeRequest)

	if err != nil {
		return err
	}

	*o = ObjectAttributeRequest(varObjectAttributeRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "attribute_id")
		delete(additionalProperties, "managed")
		delete(additionalProperties, "label")
		delete(additionalProperties, "key")
		delete(additionalProperties, "type")
		delete(additionalProperties, "flag_unique")
		delete(additionalProperties, "flag_required")
		delete(additionalProperties, "regex")
		delete(additionalProperties, "is_array")
		delete(additionalProperties, "object_type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableObjectAttributeRequest struct {
	value *ObjectAttributeRequest
	isSet bool
}

func (v NullableObjectAttributeRequest) Get() *ObjectAttributeRequest {
	return v.value
}

func (v *NullableObjectAttributeRequest) Set(val *ObjectAttributeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableObjectAttributeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableObjectAttributeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObjectAttributeRequest(val *ObjectAttributeRequest) *NullableObjectAttributeRequest {
	return &NullableObjectAttributeRequest{value: val, isSet: true}
}

func (v NullableObjectAttributeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObjectAttributeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
