/*
authentik

Making authentication simple.

API version: 2026.5.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the ObjectAttribute type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ObjectAttribute{}

// ObjectAttribute struct for ObjectAttribute
type ObjectAttribute struct {
	Pk          string                  `json:"pk"`
	ContentType ContentType             `json:"content_type"`
	Created     time.Time               `json:"created"`
	Key         string                  `json:"key"`
	Label       string                  `json:"label"`
	LastUpdated time.Time               `json:"last_updated"`
	ObjectType  int32                   `json:"object_type"`
	Regex       *string                 `json:"regex,omitempty"`
	Type        ObjectAttributeTypeEnum `json:"type"`
	// Objects that are managed by authentik. These objects are created and updated automatically. This flag only indicates that an object can be overwritten by migrations. You can still modify the objects via the API, but expect changes to be overwritten in a later update.
	Managed              NullableString `json:"managed"`
	FlagUnique           *bool          `json:"flag_unique,omitempty"`
	FlagRequired         *bool          `json:"flag_required,omitempty"`
	IsArray              *bool          `json:"is_array,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ObjectAttribute ObjectAttribute

// NewObjectAttribute instantiates a new ObjectAttribute object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObjectAttribute(pk string, contentType ContentType, created time.Time, key string, label string, lastUpdated time.Time, objectType int32, type_ ObjectAttributeTypeEnum, managed NullableString) *ObjectAttribute {
	this := ObjectAttribute{}
	this.Pk = pk
	this.ContentType = contentType
	this.Created = created
	this.Key = key
	this.Label = label
	this.LastUpdated = lastUpdated
	this.ObjectType = objectType
	this.Type = type_
	this.Managed = managed
	return &this
}

// NewObjectAttributeWithDefaults instantiates a new ObjectAttribute object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObjectAttributeWithDefaults() *ObjectAttribute {
	this := ObjectAttribute{}
	return &this
}

// GetPk returns the Pk field value
func (o *ObjectAttribute) GetPk() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Pk
}

// GetPkOk returns a tuple with the Pk field value
// and a boolean to check if the value has been set.
func (o *ObjectAttribute) GetPkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pk, true
}

// SetPk sets field value
func (o *ObjectAttribute) SetPk(v string) {
	o.Pk = v
}

// GetContentType returns the ContentType field value
func (o *ObjectAttribute) GetContentType() ContentType {
	if o == nil {
		var ret ContentType
		return ret
	}

	return o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value
// and a boolean to check if the value has been set.
func (o *ObjectAttribute) GetContentTypeOk() (*ContentType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentType, true
}

// SetContentType sets field value
func (o *ObjectAttribute) SetContentType(v ContentType) {
	o.ContentType = v
}

// GetCreated returns the Created field value
func (o *ObjectAttribute) GetCreated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *ObjectAttribute) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *ObjectAttribute) SetCreated(v time.Time) {
	o.Created = v
}

// GetKey returns the Key field value
func (o *ObjectAttribute) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *ObjectAttribute) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *ObjectAttribute) SetKey(v string) {
	o.Key = v
}

// GetLabel returns the Label field value
func (o *ObjectAttribute) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *ObjectAttribute) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *ObjectAttribute) SetLabel(v string) {
	o.Label = v
}

// GetLastUpdated returns the LastUpdated field value
func (o *ObjectAttribute) GetLastUpdated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastUpdated
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value
// and a boolean to check if the value has been set.
func (o *ObjectAttribute) GetLastUpdatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastUpdated, true
}

// SetLastUpdated sets field value
func (o *ObjectAttribute) SetLastUpdated(v time.Time) {
	o.LastUpdated = v
}

// GetObjectType returns the ObjectType field value
func (o *ObjectAttribute) GetObjectType() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value
// and a boolean to check if the value has been set.
func (o *ObjectAttribute) GetObjectTypeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectType, true
}

// SetObjectType sets field value
func (o *ObjectAttribute) SetObjectType(v int32) {
	o.ObjectType = v
}

// GetRegex returns the Regex field value if set, zero value otherwise.
func (o *ObjectAttribute) GetRegex() string {
	if o == nil || IsNil(o.Regex) {
		var ret string
		return ret
	}
	return *o.Regex
}

// GetRegexOk returns a tuple with the Regex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectAttribute) GetRegexOk() (*string, bool) {
	if o == nil || IsNil(o.Regex) {
		return nil, false
	}
	return o.Regex, true
}

// HasRegex returns a boolean if a field has been set.
func (o *ObjectAttribute) HasRegex() bool {
	if o != nil && !IsNil(o.Regex) {
		return true
	}

	return false
}

// SetRegex gets a reference to the given string and assigns it to the Regex field.
func (o *ObjectAttribute) SetRegex(v string) {
	o.Regex = &v
}

// GetType returns the Type field value
func (o *ObjectAttribute) GetType() ObjectAttributeTypeEnum {
	if o == nil {
		var ret ObjectAttributeTypeEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ObjectAttribute) GetTypeOk() (*ObjectAttributeTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ObjectAttribute) SetType(v ObjectAttributeTypeEnum) {
	o.Type = v
}

// GetManaged returns the Managed field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ObjectAttribute) GetManaged() string {
	if o == nil || o.Managed.Get() == nil {
		var ret string
		return ret
	}

	return *o.Managed.Get()
}

// GetManagedOk returns a tuple with the Managed field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ObjectAttribute) GetManagedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Managed.Get(), o.Managed.IsSet()
}

// SetManaged sets field value
func (o *ObjectAttribute) SetManaged(v string) {
	o.Managed.Set(&v)
}

// GetFlagUnique returns the FlagUnique field value if set, zero value otherwise.
func (o *ObjectAttribute) GetFlagUnique() bool {
	if o == nil || IsNil(o.FlagUnique) {
		var ret bool
		return ret
	}
	return *o.FlagUnique
}

// GetFlagUniqueOk returns a tuple with the FlagUnique field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectAttribute) GetFlagUniqueOk() (*bool, bool) {
	if o == nil || IsNil(o.FlagUnique) {
		return nil, false
	}
	return o.FlagUnique, true
}

// HasFlagUnique returns a boolean if a field has been set.
func (o *ObjectAttribute) HasFlagUnique() bool {
	if o != nil && !IsNil(o.FlagUnique) {
		return true
	}

	return false
}

// SetFlagUnique gets a reference to the given bool and assigns it to the FlagUnique field.
func (o *ObjectAttribute) SetFlagUnique(v bool) {
	o.FlagUnique = &v
}

// GetFlagRequired returns the FlagRequired field value if set, zero value otherwise.
func (o *ObjectAttribute) GetFlagRequired() bool {
	if o == nil || IsNil(o.FlagRequired) {
		var ret bool
		return ret
	}
	return *o.FlagRequired
}

// GetFlagRequiredOk returns a tuple with the FlagRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectAttribute) GetFlagRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.FlagRequired) {
		return nil, false
	}
	return o.FlagRequired, true
}

// HasFlagRequired returns a boolean if a field has been set.
func (o *ObjectAttribute) HasFlagRequired() bool {
	if o != nil && !IsNil(o.FlagRequired) {
		return true
	}

	return false
}

// SetFlagRequired gets a reference to the given bool and assigns it to the FlagRequired field.
func (o *ObjectAttribute) SetFlagRequired(v bool) {
	o.FlagRequired = &v
}

// GetIsArray returns the IsArray field value if set, zero value otherwise.
func (o *ObjectAttribute) GetIsArray() bool {
	if o == nil || IsNil(o.IsArray) {
		var ret bool
		return ret
	}
	return *o.IsArray
}

// GetIsArrayOk returns a tuple with the IsArray field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectAttribute) GetIsArrayOk() (*bool, bool) {
	if o == nil || IsNil(o.IsArray) {
		return nil, false
	}
	return o.IsArray, true
}

// HasIsArray returns a boolean if a field has been set.
func (o *ObjectAttribute) HasIsArray() bool {
	if o != nil && !IsNil(o.IsArray) {
		return true
	}

	return false
}

// SetIsArray gets a reference to the given bool and assigns it to the IsArray field.
func (o *ObjectAttribute) SetIsArray(v bool) {
	o.IsArray = &v
}

func (o ObjectAttribute) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ObjectAttribute) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pk"] = o.Pk
	toSerialize["content_type"] = o.ContentType
	toSerialize["created"] = o.Created
	toSerialize["key"] = o.Key
	toSerialize["label"] = o.Label
	toSerialize["last_updated"] = o.LastUpdated
	toSerialize["object_type"] = o.ObjectType
	if !IsNil(o.Regex) {
		toSerialize["regex"] = o.Regex
	}
	toSerialize["type"] = o.Type
	toSerialize["managed"] = o.Managed.Get()
	if !IsNil(o.FlagUnique) {
		toSerialize["flag_unique"] = o.FlagUnique
	}
	if !IsNil(o.FlagRequired) {
		toSerialize["flag_required"] = o.FlagRequired
	}
	if !IsNil(o.IsArray) {
		toSerialize["is_array"] = o.IsArray
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ObjectAttribute) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pk",
		"content_type",
		"created",
		"key",
		"label",
		"last_updated",
		"object_type",
		"type",
		"managed",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varObjectAttribute := _ObjectAttribute{}

	err = json.Unmarshal(data, &varObjectAttribute)

	if err != nil {
		return err
	}

	*o = ObjectAttribute(varObjectAttribute)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pk")
		delete(additionalProperties, "content_type")
		delete(additionalProperties, "created")
		delete(additionalProperties, "key")
		delete(additionalProperties, "label")
		delete(additionalProperties, "last_updated")
		delete(additionalProperties, "object_type")
		delete(additionalProperties, "regex")
		delete(additionalProperties, "type")
		delete(additionalProperties, "managed")
		delete(additionalProperties, "flag_unique")
		delete(additionalProperties, "flag_required")
		delete(additionalProperties, "is_array")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableObjectAttribute struct {
	value *ObjectAttribute
	isSet bool
}

func (v NullableObjectAttribute) Get() *ObjectAttribute {
	return v.value
}

func (v *NullableObjectAttribute) Set(val *ObjectAttribute) {
	v.value = val
	v.isSet = true
}

func (v NullableObjectAttribute) IsSet() bool {
	return v.isSet
}

func (v *NullableObjectAttribute) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObjectAttribute(val *ObjectAttribute) *NullableObjectAttribute {
	return &NullableObjectAttribute{value: val, isSet: true}
}

func (v NullableObjectAttribute) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObjectAttribute) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
