/*
authentik

Making authentication simple.

API version: 2026.5.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the PatchedObjectAttributeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedObjectAttributeRequest{}

// PatchedObjectAttributeRequest struct for PatchedObjectAttributeRequest
type PatchedObjectAttributeRequest struct {
	ObjectType           *string                  `json:"object_type,omitempty"`
	Enabled              *bool                    `json:"enabled,omitempty"`
	Key                  *string                  `json:"key,omitempty"`
	Label                *string                  `json:"label,omitempty"`
	Regex                *string                  `json:"regex,omitempty"`
	Type                 *ObjectAttributeTypeEnum `json:"type,omitempty"`
	FlagUnique           *bool                    `json:"flag_unique,omitempty"`
	FlagRequired         *bool                    `json:"flag_required,omitempty"`
	IsArray              *bool                    `json:"is_array,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PatchedObjectAttributeRequest PatchedObjectAttributeRequest

// NewPatchedObjectAttributeRequest instantiates a new PatchedObjectAttributeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedObjectAttributeRequest() *PatchedObjectAttributeRequest {
	this := PatchedObjectAttributeRequest{}
	return &this
}

// NewPatchedObjectAttributeRequestWithDefaults instantiates a new PatchedObjectAttributeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedObjectAttributeRequestWithDefaults() *PatchedObjectAttributeRequest {
	this := PatchedObjectAttributeRequest{}
	return &this
}

// GetObjectType returns the ObjectType field value if set, zero value otherwise.
func (o *PatchedObjectAttributeRequest) GetObjectType() string {
	if o == nil || IsNil(o.ObjectType) {
		var ret string
		return ret
	}
	return *o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedObjectAttributeRequest) GetObjectTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ObjectType) {
		return nil, false
	}
	return o.ObjectType, true
}

// HasObjectType returns a boolean if a field has been set.
func (o *PatchedObjectAttributeRequest) HasObjectType() bool {
	if o != nil && !IsNil(o.ObjectType) {
		return true
	}

	return false
}

// SetObjectType gets a reference to the given string and assigns it to the ObjectType field.
func (o *PatchedObjectAttributeRequest) SetObjectType(v string) {
	o.ObjectType = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *PatchedObjectAttributeRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedObjectAttributeRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *PatchedObjectAttributeRequest) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *PatchedObjectAttributeRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *PatchedObjectAttributeRequest) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedObjectAttributeRequest) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *PatchedObjectAttributeRequest) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *PatchedObjectAttributeRequest) SetKey(v string) {
	o.Key = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *PatchedObjectAttributeRequest) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedObjectAttributeRequest) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *PatchedObjectAttributeRequest) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *PatchedObjectAttributeRequest) SetLabel(v string) {
	o.Label = &v
}

// GetRegex returns the Regex field value if set, zero value otherwise.
func (o *PatchedObjectAttributeRequest) GetRegex() string {
	if o == nil || IsNil(o.Regex) {
		var ret string
		return ret
	}
	return *o.Regex
}

// GetRegexOk returns a tuple with the Regex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedObjectAttributeRequest) GetRegexOk() (*string, bool) {
	if o == nil || IsNil(o.Regex) {
		return nil, false
	}
	return o.Regex, true
}

// HasRegex returns a boolean if a field has been set.
func (o *PatchedObjectAttributeRequest) HasRegex() bool {
	if o != nil && !IsNil(o.Regex) {
		return true
	}

	return false
}

// SetRegex gets a reference to the given string and assigns it to the Regex field.
func (o *PatchedObjectAttributeRequest) SetRegex(v string) {
	o.Regex = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *PatchedObjectAttributeRequest) GetType() ObjectAttributeTypeEnum {
	if o == nil || IsNil(o.Type) {
		var ret ObjectAttributeTypeEnum
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedObjectAttributeRequest) GetTypeOk() (*ObjectAttributeTypeEnum, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *PatchedObjectAttributeRequest) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given ObjectAttributeTypeEnum and assigns it to the Type field.
func (o *PatchedObjectAttributeRequest) SetType(v ObjectAttributeTypeEnum) {
	o.Type = &v
}

// GetFlagUnique returns the FlagUnique field value if set, zero value otherwise.
func (o *PatchedObjectAttributeRequest) GetFlagUnique() bool {
	if o == nil || IsNil(o.FlagUnique) {
		var ret bool
		return ret
	}
	return *o.FlagUnique
}

// GetFlagUniqueOk returns a tuple with the FlagUnique field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedObjectAttributeRequest) GetFlagUniqueOk() (*bool, bool) {
	if o == nil || IsNil(o.FlagUnique) {
		return nil, false
	}
	return o.FlagUnique, true
}

// HasFlagUnique returns a boolean if a field has been set.
func (o *PatchedObjectAttributeRequest) HasFlagUnique() bool {
	if o != nil && !IsNil(o.FlagUnique) {
		return true
	}

	return false
}

// SetFlagUnique gets a reference to the given bool and assigns it to the FlagUnique field.
func (o *PatchedObjectAttributeRequest) SetFlagUnique(v bool) {
	o.FlagUnique = &v
}

// GetFlagRequired returns the FlagRequired field value if set, zero value otherwise.
func (o *PatchedObjectAttributeRequest) GetFlagRequired() bool {
	if o == nil || IsNil(o.FlagRequired) {
		var ret bool
		return ret
	}
	return *o.FlagRequired
}

// GetFlagRequiredOk returns a tuple with the FlagRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedObjectAttributeRequest) GetFlagRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.FlagRequired) {
		return nil, false
	}
	return o.FlagRequired, true
}

// HasFlagRequired returns a boolean if a field has been set.
func (o *PatchedObjectAttributeRequest) HasFlagRequired() bool {
	if o != nil && !IsNil(o.FlagRequired) {
		return true
	}

	return false
}

// SetFlagRequired gets a reference to the given bool and assigns it to the FlagRequired field.
func (o *PatchedObjectAttributeRequest) SetFlagRequired(v bool) {
	o.FlagRequired = &v
}

// GetIsArray returns the IsArray field value if set, zero value otherwise.
func (o *PatchedObjectAttributeRequest) GetIsArray() bool {
	if o == nil || IsNil(o.IsArray) {
		var ret bool
		return ret
	}
	return *o.IsArray
}

// GetIsArrayOk returns a tuple with the IsArray field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedObjectAttributeRequest) GetIsArrayOk() (*bool, bool) {
	if o == nil || IsNil(o.IsArray) {
		return nil, false
	}
	return o.IsArray, true
}

// HasIsArray returns a boolean if a field has been set.
func (o *PatchedObjectAttributeRequest) HasIsArray() bool {
	if o != nil && !IsNil(o.IsArray) {
		return true
	}

	return false
}

// SetIsArray gets a reference to the given bool and assigns it to the IsArray field.
func (o *PatchedObjectAttributeRequest) SetIsArray(v bool) {
	o.IsArray = &v
}

func (o PatchedObjectAttributeRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedObjectAttributeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ObjectType) {
		toSerialize["object_type"] = o.ObjectType
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.Regex) {
		toSerialize["regex"] = o.Regex
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.FlagUnique) {
		toSerialize["flag_unique"] = o.FlagUnique
	}
	if !IsNil(o.FlagRequired) {
		toSerialize["flag_required"] = o.FlagRequired
	}
	if !IsNil(o.IsArray) {
		toSerialize["is_array"] = o.IsArray
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PatchedObjectAttributeRequest) UnmarshalJSON(data []byte) (err error) {
	varPatchedObjectAttributeRequest := _PatchedObjectAttributeRequest{}

	err = json.Unmarshal(data, &varPatchedObjectAttributeRequest)

	if err != nil {
		return err
	}

	*o = PatchedObjectAttributeRequest(varPatchedObjectAttributeRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "object_type")
		delete(additionalProperties, "enabled")
		delete(additionalProperties, "key")
		delete(additionalProperties, "label")
		delete(additionalProperties, "regex")
		delete(additionalProperties, "type")
		delete(additionalProperties, "flag_unique")
		delete(additionalProperties, "flag_required")
		delete(additionalProperties, "is_array")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePatchedObjectAttributeRequest struct {
	value *PatchedObjectAttributeRequest
	isSet bool
}

func (v NullablePatchedObjectAttributeRequest) Get() *PatchedObjectAttributeRequest {
	return v.value
}

func (v *NullablePatchedObjectAttributeRequest) Set(val *PatchedObjectAttributeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedObjectAttributeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedObjectAttributeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedObjectAttributeRequest(val *PatchedObjectAttributeRequest) *NullablePatchedObjectAttributeRequest {
	return &NullablePatchedObjectAttributeRequest{value: val, isSet: true}
}

func (v NullablePatchedObjectAttributeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedObjectAttributeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
