/*
authentik

Making authentication simple.

API version: 2026.5.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the UserAgentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserAgentRequest{}

// UserAgentRequest Payload to create an agent user
type UserAgentRequest struct {
	Name                 string `json:"name"`
	AdditionalProperties map[string]interface{}
}

type _UserAgentRequest UserAgentRequest

// NewUserAgentRequest instantiates a new UserAgentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserAgentRequest(name string) *UserAgentRequest {
	this := UserAgentRequest{}
	this.Name = name
	return &this
}

// NewUserAgentRequestWithDefaults instantiates a new UserAgentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserAgentRequestWithDefaults() *UserAgentRequest {
	this := UserAgentRequest{}
	return &this
}

// GetName returns the Name field value
func (o *UserAgentRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UserAgentRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UserAgentRequest) SetName(v string) {
	o.Name = v
}

func (o UserAgentRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserAgentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UserAgentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserAgentRequest := _UserAgentRequest{}

	err = json.Unmarshal(data, &varUserAgentRequest)

	if err != nil {
		return err
	}

	*o = UserAgentRequest(varUserAgentRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUserAgentRequest struct {
	value *UserAgentRequest
	isSet bool
}

func (v NullableUserAgentRequest) Get() *UserAgentRequest {
	return v.value
}

func (v *NullableUserAgentRequest) Set(val *UserAgentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUserAgentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUserAgentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserAgentRequest(val *UserAgentRequest) *NullableUserAgentRequest {
	return &NullableUserAgentRequest{value: val, isSet: true}
}

func (v NullableUserAgentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserAgentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
