/*
authentik

Making authentication simple.

API version: 2026.5.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the ThemedUrls type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ThemedUrls{}

// ThemedUrls URL variants keyed by theme name. Includes a fallback URL.
type ThemedUrls struct {
	Fallback             NullableString `json:"fallback,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ThemedUrls ThemedUrls

// NewThemedUrls instantiates a new ThemedUrls object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewThemedUrls() *ThemedUrls {
	this := ThemedUrls{}
	return &this
}

// NewThemedUrlsWithDefaults instantiates a new ThemedUrls object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewThemedUrlsWithDefaults() *ThemedUrls {
	this := ThemedUrls{}
	return &this
}

// GetFallback returns the Fallback field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ThemedUrls) GetFallback() string {
	if o == nil || IsNil(o.Fallback.Get()) {
		var ret string
		return ret
	}
	return *o.Fallback.Get()
}

// GetFallbackOk returns a tuple with the Fallback field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ThemedUrls) GetFallbackOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Fallback.Get(), o.Fallback.IsSet()
}

// HasFallback returns a boolean if a field has been set.
func (o *ThemedUrls) HasFallback() bool {
	if o != nil && o.Fallback.IsSet() {
		return true
	}

	return false
}

// SetFallback gets a reference to the given NullableString and assigns it to the Fallback field.
func (o *ThemedUrls) SetFallback(v string) {
	o.Fallback.Set(&v)
}

// SetFallbackNil sets the value for Fallback to be an explicit nil
func (o *ThemedUrls) SetFallbackNil() {
	o.Fallback.Set(nil)
}

// UnsetFallback ensures that no value is present for Fallback, not even an explicit nil
func (o *ThemedUrls) UnsetFallback() {
	o.Fallback.Unset()
}

func (o ThemedUrls) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ThemedUrls) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Fallback.IsSet() {
		toSerialize["fallback"] = o.Fallback.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ThemedUrls) UnmarshalJSON(data []byte) (err error) {
	varThemedUrls := _ThemedUrls{}

	err = json.Unmarshal(data, &varThemedUrls)

	if err != nil {
		return err
	}

	*o = ThemedUrls(varThemedUrls)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "fallback")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableThemedUrls struct {
	value *ThemedUrls
	isSet bool
}

func (v NullableThemedUrls) Get() *ThemedUrls {
	return v.value
}

func (v *NullableThemedUrls) Set(val *ThemedUrls) {
	v.value = val
	v.isSet = true
}

func (v NullableThemedUrls) IsSet() bool {
	return v.isSet
}

func (v *NullableThemedUrls) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableThemedUrls(val *ThemedUrls) *NullableThemedUrls {
	return &NullableThemedUrls{value: val, isSet: true}
}

func (v NullableThemedUrls) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableThemedUrls) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
