/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Dynamic URL variants keyed by variant name. Includes a fallback URL.
 * @export
 * @interface DynamicURL
 */
export interface DynamicURL {
    [key: string]: string | any;
    /**
     *
     * @type {string}
     * @memberof DynamicURL
     */
    fallback?: string | null;
}

/**
 * Check if a given object implements the DynamicURL interface.
 */
export function instanceOfDynamicURL(value: object): value is DynamicURL {
    return true;
}

export function DynamicURLFromJSON(json: any): DynamicURL {
    return DynamicURLFromJSONTyped(json, false);
}

export function DynamicURLFromJSONTyped(json: any, ignoreDiscriminator: boolean): DynamicURL {
    if (json == null) {
        return json;
    }
    return {
        ...json,
        fallback: json["fallback"] == null ? undefined : json["fallback"],
    };
}

export function DynamicURLToJSON(json: any): DynamicURL {
    return DynamicURLToJSONTyped(json, false);
}

export function DynamicURLToJSONTyped(
    value?: DynamicURL | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        ...value,
        fallback: value["fallback"],
    };
}
