/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ContentType } from "./ContentType";
import { ContentTypeFromJSON } from "./ContentType";
import type { ObjectAttributeTypeEnum } from "./ObjectAttributeTypeEnum";
import {
    ObjectAttributeTypeEnumFromJSON,
    ObjectAttributeTypeEnumToJSON,
} from "./ObjectAttributeTypeEnum";

/**
 *
 * @export
 * @interface ObjectAttribute
 */
export interface ObjectAttribute {
    /**
     *
     * @type {string}
     * @memberof ObjectAttribute
     */
    attributeId?: string;
    /**
     *
     * @type {ContentType}
     * @memberof ObjectAttribute
     */
    readonly contentType: ContentType;
    /**
     *
     * @type {Date}
     * @memberof ObjectAttribute
     */
    readonly created: Date;
    /**
     *
     * @type {Date}
     * @memberof ObjectAttribute
     */
    readonly lastUpdated: Date;
    /**
     * Objects that are managed by authentik. These objects are created and updated automatically. This flag only indicates that an object can be overwritten by migrations. You can still modify the objects via the API, but expect changes to be overwritten in a later update.
     * @type {string}
     * @memberof ObjectAttribute
     */
    managed?: string | null;
    /**
     *
     * @type {string}
     * @memberof ObjectAttribute
     */
    label: string;
    /**
     *
     * @type {string}
     * @memberof ObjectAttribute
     */
    key: string;
    /**
     *
     * @type {ObjectAttributeTypeEnum}
     * @memberof ObjectAttribute
     */
    type: ObjectAttributeTypeEnum;
    /**
     *
     * @type {boolean}
     * @memberof ObjectAttribute
     */
    flagUnique?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ObjectAttribute
     */
    flagRequired?: boolean;
    /**
     *
     * @type {string}
     * @memberof ObjectAttribute
     */
    regex: string;
    /**
     *
     * @type {boolean}
     * @memberof ObjectAttribute
     */
    isArray?: boolean;
    /**
     *
     * @type {number}
     * @memberof ObjectAttribute
     */
    objectType: number;
}

/**
 * Check if a given object implements the ObjectAttribute interface.
 */
export function instanceOfObjectAttribute(value: object): value is ObjectAttribute {
    if (!("contentType" in value) || value["contentType"] === undefined) return false;
    if (!("created" in value) || value["created"] === undefined) return false;
    if (!("lastUpdated" in value) || value["lastUpdated"] === undefined) return false;
    if (!("label" in value) || value["label"] === undefined) return false;
    if (!("key" in value) || value["key"] === undefined) return false;
    if (!("type" in value) || value["type"] === undefined) return false;
    if (!("regex" in value) || value["regex"] === undefined) return false;
    if (!("objectType" in value) || value["objectType"] === undefined) return false;
    return true;
}

export function ObjectAttributeFromJSON(json: any): ObjectAttribute {
    return ObjectAttributeFromJSONTyped(json, false);
}

export function ObjectAttributeFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): ObjectAttribute {
    if (json == null) {
        return json;
    }
    return {
        attributeId: json["attribute_id"] == null ? undefined : json["attribute_id"],
        contentType: ContentTypeFromJSON(json["content_type"]),
        created: new Date(json["created"]),
        lastUpdated: new Date(json["last_updated"]),
        managed: json["managed"] == null ? undefined : json["managed"],
        label: json["label"],
        key: json["key"],
        type: ObjectAttributeTypeEnumFromJSON(json["type"]),
        flagUnique: json["flag_unique"] == null ? undefined : json["flag_unique"],
        flagRequired: json["flag_required"] == null ? undefined : json["flag_required"],
        regex: json["regex"],
        isArray: json["is_array"] == null ? undefined : json["is_array"],
        objectType: json["object_type"],
    };
}

export function ObjectAttributeToJSON(json: any): ObjectAttribute {
    return ObjectAttributeToJSONTyped(json, false);
}

export function ObjectAttributeToJSONTyped(
    value?: Omit<ObjectAttribute, "content_type" | "created" | "last_updated"> | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        attribute_id: value["attributeId"],
        managed: value["managed"],
        label: value["label"],
        key: value["key"],
        type: ObjectAttributeTypeEnumToJSON(value["type"]),
        flag_unique: value["flagUnique"],
        flag_required: value["flagRequired"],
        regex: value["regex"],
        is_array: value["isArray"],
        object_type: value["objectType"],
    };
}
