/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ObjectAttributeTypeEnum } from "./ObjectAttributeTypeEnum";
import {
    ObjectAttributeTypeEnumFromJSON,
    ObjectAttributeTypeEnumToJSON,
} from "./ObjectAttributeTypeEnum";

/**
 *
 * @export
 * @interface ObjectAttributeRequest
 */
export interface ObjectAttributeRequest {
    /**
     *
     * @type {string}
     * @memberof ObjectAttributeRequest
     */
    attributeId?: string;
    /**
     * Objects that are managed by authentik. These objects are created and updated automatically. This flag only indicates that an object can be overwritten by migrations. You can still modify the objects via the API, but expect changes to be overwritten in a later update.
     * @type {string}
     * @memberof ObjectAttributeRequest
     */
    managed?: string | null;
    /**
     *
     * @type {string}
     * @memberof ObjectAttributeRequest
     */
    label: string;
    /**
     *
     * @type {string}
     * @memberof ObjectAttributeRequest
     */
    key: string;
    /**
     *
     * @type {ObjectAttributeTypeEnum}
     * @memberof ObjectAttributeRequest
     */
    type: ObjectAttributeTypeEnum;
    /**
     *
     * @type {boolean}
     * @memberof ObjectAttributeRequest
     */
    flagUnique?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ObjectAttributeRequest
     */
    flagRequired?: boolean;
    /**
     *
     * @type {string}
     * @memberof ObjectAttributeRequest
     */
    regex: string;
    /**
     *
     * @type {boolean}
     * @memberof ObjectAttributeRequest
     */
    isArray?: boolean;
    /**
     *
     * @type {number}
     * @memberof ObjectAttributeRequest
     */
    objectType: number;
}

/**
 * Check if a given object implements the ObjectAttributeRequest interface.
 */
export function instanceOfObjectAttributeRequest(value: object): value is ObjectAttributeRequest {
    if (!("label" in value) || value["label"] === undefined) return false;
    if (!("key" in value) || value["key"] === undefined) return false;
    if (!("type" in value) || value["type"] === undefined) return false;
    if (!("regex" in value) || value["regex"] === undefined) return false;
    if (!("objectType" in value) || value["objectType"] === undefined) return false;
    return true;
}

export function ObjectAttributeRequestFromJSON(json: any): ObjectAttributeRequest {
    return ObjectAttributeRequestFromJSONTyped(json, false);
}

export function ObjectAttributeRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): ObjectAttributeRequest {
    if (json == null) {
        return json;
    }
    return {
        attributeId: json["attribute_id"] == null ? undefined : json["attribute_id"],
        managed: json["managed"] == null ? undefined : json["managed"],
        label: json["label"],
        key: json["key"],
        type: ObjectAttributeTypeEnumFromJSON(json["type"]),
        flagUnique: json["flag_unique"] == null ? undefined : json["flag_unique"],
        flagRequired: json["flag_required"] == null ? undefined : json["flag_required"],
        regex: json["regex"],
        isArray: json["is_array"] == null ? undefined : json["is_array"],
        objectType: json["object_type"],
    };
}

export function ObjectAttributeRequestToJSON(json: any): ObjectAttributeRequest {
    return ObjectAttributeRequestToJSONTyped(json, false);
}

export function ObjectAttributeRequestToJSONTyped(
    value?: ObjectAttributeRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        attribute_id: value["attributeId"],
        managed: value["managed"],
        label: value["label"],
        key: value["key"],
        type: ObjectAttributeTypeEnumToJSON(value["type"]),
        flag_unique: value["flagUnique"],
        flag_required: value["flagRequired"],
        regex: value["regex"],
        is_array: value["isArray"],
        object_type: value["objectType"],
    };
}
