/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ObjectAttributeTypeEnum } from "./ObjectAttributeTypeEnum";
import {
    ObjectAttributeTypeEnumFromJSON,
    ObjectAttributeTypeEnumToJSON,
} from "./ObjectAttributeTypeEnum";

/**
 *
 * @export
 * @interface ObjectAttributeRequest
 */
export interface ObjectAttributeRequest {
    /**
     *
     * @type {string}
     * @memberof ObjectAttributeRequest
     */
    objectType: string;
    /**
     *
     * @type {boolean}
     * @memberof ObjectAttributeRequest
     */
    enabled?: boolean;
    /**
     *
     * @type {string}
     * @memberof ObjectAttributeRequest
     */
    key: string;
    /**
     *
     * @type {string}
     * @memberof ObjectAttributeRequest
     */
    label: string;
    /**
     *
     * @type {string}
     * @memberof ObjectAttributeRequest
     */
    regex?: string;
    /**
     *
     * @type {ObjectAttributeTypeEnum}
     * @memberof ObjectAttributeRequest
     */
    type: ObjectAttributeTypeEnum;
    /**
     *
     * @type {string}
     * @memberof ObjectAttributeRequest
     */
    group?: string;
    /**
     *
     * @type {boolean}
     * @memberof ObjectAttributeRequest
     */
    flagUnique?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ObjectAttributeRequest
     */
    flagRequired?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ObjectAttributeRequest
     */
    isArray?: boolean;
}

/**
 * Check if a given object implements the ObjectAttributeRequest interface.
 */
export function instanceOfObjectAttributeRequest(value: object): value is ObjectAttributeRequest {
    if (!("objectType" in value) || value["objectType"] === undefined) return false;
    if (!("key" in value) || value["key"] === undefined) return false;
    if (!("label" in value) || value["label"] === undefined) return false;
    if (!("type" in value) || value["type"] === undefined) return false;
    return true;
}

export function ObjectAttributeRequestFromJSON(json: any): ObjectAttributeRequest {
    return ObjectAttributeRequestFromJSONTyped(json, false);
}

export function ObjectAttributeRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): ObjectAttributeRequest {
    if (json == null) {
        return json;
    }
    return {
        objectType: json["object_type"],
        enabled: json["enabled"] == null ? undefined : json["enabled"],
        key: json["key"],
        label: json["label"],
        regex: json["regex"] == null ? undefined : json["regex"],
        type: ObjectAttributeTypeEnumFromJSON(json["type"]),
        group: json["group"] == null ? undefined : json["group"],
        flagUnique: json["flag_unique"] == null ? undefined : json["flag_unique"],
        flagRequired: json["flag_required"] == null ? undefined : json["flag_required"],
        isArray: json["is_array"] == null ? undefined : json["is_array"],
    };
}

export function ObjectAttributeRequestToJSON(json: any): ObjectAttributeRequest {
    return ObjectAttributeRequestToJSONTyped(json, false);
}

export function ObjectAttributeRequestToJSONTyped(
    value?: ObjectAttributeRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        object_type: value["objectType"],
        enabled: value["enabled"],
        key: value["key"],
        label: value["label"],
        regex: value["regex"],
        type: ObjectAttributeTypeEnumToJSON(value["type"]),
        group: value["group"],
        flag_unique: value["flagUnique"],
        flag_required: value["flagRequired"],
        is_array: value["isArray"],
    };
}
