/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ObjectAttributeTypeEnum } from "./ObjectAttributeTypeEnum";
import {
    ObjectAttributeTypeEnumFromJSON,
    ObjectAttributeTypeEnumToJSON,
} from "./ObjectAttributeTypeEnum";

/**
 *
 * @export
 * @interface PatchedObjectAttributeRequest
 */
export interface PatchedObjectAttributeRequest {
    /**
     *
     * @type {string}
     * @memberof PatchedObjectAttributeRequest
     */
    attributeId?: string;
    /**
     * Objects that are managed by authentik. These objects are created and updated automatically. This flag only indicates that an object can be overwritten by migrations. You can still modify the objects via the API, but expect changes to be overwritten in a later update.
     * @type {string}
     * @memberof PatchedObjectAttributeRequest
     */
    managed?: string | null;
    /**
     *
     * @type {string}
     * @memberof PatchedObjectAttributeRequest
     */
    label?: string;
    /**
     *
     * @type {string}
     * @memberof PatchedObjectAttributeRequest
     */
    key?: string;
    /**
     *
     * @type {ObjectAttributeTypeEnum}
     * @memberof PatchedObjectAttributeRequest
     */
    type?: ObjectAttributeTypeEnum;
    /**
     *
     * @type {boolean}
     * @memberof PatchedObjectAttributeRequest
     */
    flagUnique?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof PatchedObjectAttributeRequest
     */
    flagRequired?: boolean;
    /**
     *
     * @type {string}
     * @memberof PatchedObjectAttributeRequest
     */
    regex?: string;
    /**
     *
     * @type {boolean}
     * @memberof PatchedObjectAttributeRequest
     */
    isArray?: boolean;
    /**
     *
     * @type {number}
     * @memberof PatchedObjectAttributeRequest
     */
    objectType?: number;
}

/**
 * Check if a given object implements the PatchedObjectAttributeRequest interface.
 */
export function instanceOfPatchedObjectAttributeRequest(
    value: object,
): value is PatchedObjectAttributeRequest {
    return true;
}

export function PatchedObjectAttributeRequestFromJSON(json: any): PatchedObjectAttributeRequest {
    return PatchedObjectAttributeRequestFromJSONTyped(json, false);
}

export function PatchedObjectAttributeRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PatchedObjectAttributeRequest {
    if (json == null) {
        return json;
    }
    return {
        attributeId: json["attribute_id"] == null ? undefined : json["attribute_id"],
        managed: json["managed"] == null ? undefined : json["managed"],
        label: json["label"] == null ? undefined : json["label"],
        key: json["key"] == null ? undefined : json["key"],
        type: json["type"] == null ? undefined : ObjectAttributeTypeEnumFromJSON(json["type"]),
        flagUnique: json["flag_unique"] == null ? undefined : json["flag_unique"],
        flagRequired: json["flag_required"] == null ? undefined : json["flag_required"],
        regex: json["regex"] == null ? undefined : json["regex"],
        isArray: json["is_array"] == null ? undefined : json["is_array"],
        objectType: json["object_type"] == null ? undefined : json["object_type"],
    };
}

export function PatchedObjectAttributeRequestToJSON(json: any): PatchedObjectAttributeRequest {
    return PatchedObjectAttributeRequestToJSONTyped(json, false);
}

export function PatchedObjectAttributeRequestToJSONTyped(
    value?: PatchedObjectAttributeRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        attribute_id: value["attributeId"],
        managed: value["managed"],
        label: value["label"],
        key: value["key"],
        type: ObjectAttributeTypeEnumToJSON(value["type"]),
        flag_unique: value["flagUnique"],
        flag_required: value["flagRequired"],
        regex: value["regex"],
        is_array: value["isArray"],
        object_type: value["objectType"],
    };
}
