/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ObjectAttributeTypeEnum } from "./ObjectAttributeTypeEnum";
import {
    ObjectAttributeTypeEnumFromJSON,
    ObjectAttributeTypeEnumToJSON,
} from "./ObjectAttributeTypeEnum";

/**
 *
 * @export
 * @interface PatchedObjectAttributeRequest
 */
export interface PatchedObjectAttributeRequest {
    /**
     *
     * @type {string}
     * @memberof PatchedObjectAttributeRequest
     */
    objectType?: string;
    /**
     *
     * @type {boolean}
     * @memberof PatchedObjectAttributeRequest
     */
    enabled?: boolean;
    /**
     *
     * @type {string}
     * @memberof PatchedObjectAttributeRequest
     */
    key?: string;
    /**
     *
     * @type {string}
     * @memberof PatchedObjectAttributeRequest
     */
    label?: string;
    /**
     *
     * @type {string}
     * @memberof PatchedObjectAttributeRequest
     */
    regex?: string;
    /**
     *
     * @type {ObjectAttributeTypeEnum}
     * @memberof PatchedObjectAttributeRequest
     */
    type?: ObjectAttributeTypeEnum;
    /**
     *
     * @type {boolean}
     * @memberof PatchedObjectAttributeRequest
     */
    flagUnique?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof PatchedObjectAttributeRequest
     */
    flagRequired?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof PatchedObjectAttributeRequest
     */
    isArray?: boolean;
}

/**
 * Check if a given object implements the PatchedObjectAttributeRequest interface.
 */
export function instanceOfPatchedObjectAttributeRequest(
    value: object,
): value is PatchedObjectAttributeRequest {
    return true;
}

export function PatchedObjectAttributeRequestFromJSON(json: any): PatchedObjectAttributeRequest {
    return PatchedObjectAttributeRequestFromJSONTyped(json, false);
}

export function PatchedObjectAttributeRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PatchedObjectAttributeRequest {
    if (json == null) {
        return json;
    }
    return {
        objectType: json["object_type"] == null ? undefined : json["object_type"],
        enabled: json["enabled"] == null ? undefined : json["enabled"],
        key: json["key"] == null ? undefined : json["key"],
        label: json["label"] == null ? undefined : json["label"],
        regex: json["regex"] == null ? undefined : json["regex"],
        type: json["type"] == null ? undefined : ObjectAttributeTypeEnumFromJSON(json["type"]),
        flagUnique: json["flag_unique"] == null ? undefined : json["flag_unique"],
        flagRequired: json["flag_required"] == null ? undefined : json["flag_required"],
        isArray: json["is_array"] == null ? undefined : json["is_array"],
    };
}

export function PatchedObjectAttributeRequestToJSON(json: any): PatchedObjectAttributeRequest {
    return PatchedObjectAttributeRequestToJSONTyped(json, false);
}

export function PatchedObjectAttributeRequestToJSONTyped(
    value?: PatchedObjectAttributeRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        object_type: value["objectType"],
        enabled: value["enabled"],
        key: value["key"],
        label: value["label"],
        regex: value["regex"],
        type: ObjectAttributeTypeEnumToJSON(value["type"]),
        flag_unique: value["flagUnique"],
        flag_required: value["flagRequired"],
        is_array: value["isArray"],
    };
}
