/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * URL variants keyed by theme name. Includes a fallback URL.
 * @export
 * @interface ThemedUrls
 */
export interface ThemedUrls {
    [key: string]: string | any;
    /**
     *
     * @type {string}
     * @memberof ThemedUrls
     */
    fallback?: string | null;
}

/**
 * Check if a given object implements the ThemedUrls interface.
 */
export function instanceOfThemedUrls(value: object): value is ThemedUrls {
    return true;
}

export function ThemedUrlsFromJSON(json: any): ThemedUrls {
    return ThemedUrlsFromJSONTyped(json, false);
}

export function ThemedUrlsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThemedUrls {
    if (json == null) {
        return json;
    }
    return {
        ...json,
        fallback: json["fallback"] == null ? undefined : json["fallback"],
    };
}

export function ThemedUrlsToJSON(json: any): ThemedUrls {
    return ThemedUrlsToJSONTyped(json, false);
}

export function ThemedUrlsToJSONTyped(
    value?: ThemedUrls | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        ...value,
        fallback: value["fallback"],
    };
}
