/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Payload to set a user's password from a pre-hashed Django password value.
 *
 * This only updates authentik's stored password verifier and does not propagate
 * the change to LDAP or Kerberos password-sync integrations.
 * @export
 * @interface UserPasswordHashSetRequest
 */
export interface UserPasswordHashSetRequest {
    /**
     *
     * @type {string}
     * @memberof UserPasswordHashSetRequest
     */
    passwordHash: string;
}

/**
 * Check if a given object implements the UserPasswordHashSetRequest interface.
 */
export function instanceOfUserPasswordHashSetRequest(
    value: object,
): value is UserPasswordHashSetRequest {
    if (!("passwordHash" in value) || value["passwordHash"] === undefined) return false;
    return true;
}

export function UserPasswordHashSetRequestFromJSON(json: any): UserPasswordHashSetRequest {
    return UserPasswordHashSetRequestFromJSONTyped(json, false);
}

export function UserPasswordHashSetRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): UserPasswordHashSetRequest {
    if (json == null) {
        return json;
    }
    return {
        passwordHash: json["password_hash"],
    };
}

export function UserPasswordHashSetRequestToJSON(json: any): UserPasswordHashSetRequest {
    return UserPasswordHashSetRequestToJSONTyped(json, false);
}

export function UserPasswordHashSetRequestToJSONTyped(
    value?: UserPasswordHashSetRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        password_hash: value["passwordHash"],
    };
}
