/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountLockdownFlowResponse {
    /// URL to redirect to for lockdown flow
    #[serde(rename = "flow_url")]
    pub flow_url: String,
}

impl AccountLockdownFlowResponse {
    pub fn new(flow_url: String) -> AccountLockdownFlowResponse {
        AccountLockdownFlowResponse {
            flow_url,
        }
    }
}

