// authentik
//
// Making authentication simple.
//
// The version of the OpenAPI document: 2026.5.0-rc1
// Contact: hello@goauthentik.io
// Generated by: https://openapi-generator.tech

use serde::{Deserialize, Serialize};

use crate::models;

/// DynamicUrl : Dynamic URL variants keyed by variant name. Includes a fallback URL.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DynamicUrl {
    #[serde(
        rename = "fallback",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub fallback: Option<Option<String>>,
}

impl DynamicUrl {
    /// Dynamic URL variants keyed by variant name. Includes a fallback URL.
    pub fn new() -> DynamicUrl {
        DynamicUrl { fallback: None }
    }
}
