// authentik
//
// Making authentication simple.
//
// The version of the OpenAPI document: 2026.5.0-rc1
// Contact: hello@goauthentik.io
// Generated by: https://openapi-generator.tech

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ObjectAttributeRequest {
    #[serde(rename = "attribute_id", skip_serializing_if = "Option::is_none")]
    pub attribute_id: Option<uuid::Uuid>,
    /// Objects that are managed by authentik. These objects are created and updated automatically.
    /// This flag only indicates that an object can be overwritten by migrations. You can still
    /// modify the objects via the API, but expect changes to be overwritten in a later update.
    #[serde(
        rename = "managed",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub managed: Option<Option<String>>,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "type")]
    pub r#type: models::ObjectAttributeTypeEnum,
    #[serde(rename = "flag_unique", skip_serializing_if = "Option::is_none")]
    pub flag_unique: Option<bool>,
    #[serde(rename = "flag_required", skip_serializing_if = "Option::is_none")]
    pub flag_required: Option<bool>,
    #[serde(rename = "regex")]
    pub regex: String,
    #[serde(rename = "is_array", skip_serializing_if = "Option::is_none")]
    pub is_array: Option<bool>,
    #[serde(rename = "object_type")]
    pub object_type: i32,
}

impl ObjectAttributeRequest {
    pub fn new(
        label: String,
        key: String,
        r#type: models::ObjectAttributeTypeEnum,
        regex: String,
        object_type: i32,
    ) -> ObjectAttributeRequest {
        ObjectAttributeRequest {
            attribute_id: None,
            managed: None,
            label,
            key,
            r#type,
            flag_unique: None,
            flag_required: None,
            regex,
            is_array: None,
            object_type,
        }
    }
}
