// authentik
//
// Making authentication simple.
//
// The version of the OpenAPI document: 2026.5.0-rc1
// Contact: hello@goauthentik.io
// Generated by: https://openapi-generator.tech

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ObjectAttribute {
    #[serde(rename = "pk")]
    pub pk: uuid::Uuid,
    #[serde(rename = "content_type")]
    pub content_type: models::ContentType,
    #[serde(rename = "created")]
    pub created: String,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "last_updated")]
    pub last_updated: String,
    #[serde(rename = "object_type")]
    pub object_type: i32,
    #[serde(rename = "regex", skip_serializing_if = "Option::is_none")]
    pub regex: Option<String>,
    #[serde(rename = "type")]
    pub r#type: models::ObjectAttributeTypeEnum,
    /// Objects that are managed by authentik. These objects are created and updated automatically.
    /// This flag only indicates that an object can be overwritten by migrations. You can still
    /// modify the objects via the API, but expect changes to be overwritten in a later update.
    #[serde(rename = "managed", deserialize_with = "Option::deserialize")]
    pub managed: Option<String>,
    #[serde(rename = "flag_unique", skip_serializing_if = "Option::is_none")]
    pub flag_unique: Option<bool>,
    #[serde(rename = "flag_required", skip_serializing_if = "Option::is_none")]
    pub flag_required: Option<bool>,
    #[serde(rename = "is_array", skip_serializing_if = "Option::is_none")]
    pub is_array: Option<bool>,
}

impl ObjectAttribute {
    pub fn new(
        pk: uuid::Uuid,
        content_type: models::ContentType,
        created: String,
        key: String,
        label: String,
        last_updated: String,
        object_type: i32,
        r#type: models::ObjectAttributeTypeEnum,
        managed: Option<String>,
    ) -> ObjectAttribute {
        ObjectAttribute {
            pk,
            content_type,
            created,
            key,
            label,
            last_updated,
            object_type,
            regex: None,
            r#type,
            managed,
            flag_unique: None,
            flag_required: None,
            is_array: None,
        }
    }
}
