// authentik
//
// Making authentication simple.
//
// The version of the OpenAPI document: 2026.5.0-rc1
// Contact: hello@goauthentik.io
// Generated by: https://openapi-generator.tech

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ObjectAttributeRequest {
    #[serde(rename = "object_type")]
    pub object_type: String,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "regex", skip_serializing_if = "Option::is_none")]
    pub regex: Option<String>,
    #[serde(rename = "type")]
    pub r#type: models::ObjectAttributeTypeEnum,
    #[serde(rename = "flag_unique", skip_serializing_if = "Option::is_none")]
    pub flag_unique: Option<bool>,
    #[serde(rename = "flag_required", skip_serializing_if = "Option::is_none")]
    pub flag_required: Option<bool>,
    #[serde(rename = "is_array", skip_serializing_if = "Option::is_none")]
    pub is_array: Option<bool>,
}

impl ObjectAttributeRequest {
    pub fn new(
        object_type: String,
        key: String,
        label: String,
        r#type: models::ObjectAttributeTypeEnum,
    ) -> ObjectAttributeRequest {
        ObjectAttributeRequest {
            object_type,
            enabled: None,
            key,
            label,
            regex: None,
            r#type,
            flag_unique: None,
            flag_required: None,
            is_array: None,
        }
    }
}
