// authentik
//
// Making authentication simple.
//
// The version of the OpenAPI document: 2026.5.0-rc1
// Contact: hello@goauthentik.io
// Generated by: https://openapi-generator.tech

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedObjectAttributeRequest {
    #[serde(rename = "object_type", skip_serializing_if = "Option::is_none")]
    pub object_type: Option<String>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "regex", skip_serializing_if = "Option::is_none")]
    pub regex: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::ObjectAttributeTypeEnum>,
    #[serde(rename = "flag_unique", skip_serializing_if = "Option::is_none")]
    pub flag_unique: Option<bool>,
    #[serde(rename = "flag_required", skip_serializing_if = "Option::is_none")]
    pub flag_required: Option<bool>,
    #[serde(rename = "is_array", skip_serializing_if = "Option::is_none")]
    pub is_array: Option<bool>,
}

impl PatchedObjectAttributeRequest {
    pub fn new() -> PatchedObjectAttributeRequest {
        PatchedObjectAttributeRequest {
            object_type: None,
            enabled: None,
            key: None,
            label: None,
            regex: None,
            r#type: None,
            flag_unique: None,
            flag_required: None,
            is_array: None,
        }
    }
}
