// authentik
//
// Making authentication simple.
//
// The version of the OpenAPI document: 2026.5.0-rc1
// Contact: hello@goauthentik.io
// Generated by: https://openapi-generator.tech

use serde::{Deserialize, Serialize};

use crate::models;

/// ThemedUrls : URL variants keyed by theme name. Includes a fallback URL.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThemedUrls {
    #[serde(
        rename = "fallback",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub fallback: Option<Option<String>>,
}

impl ThemedUrls {
    /// URL variants keyed by theme name. Includes a fallback URL.
    pub fn new() -> ThemedUrls {
        ThemedUrls { fallback: None }
    }
}
