// authentik
//
// Making authentication simple.
//
// The version of the OpenAPI document: 2026.5.0-rc1
// Contact: hello@goauthentik.io
// Generated by: https://openapi-generator.tech

use serde::{Deserialize, Serialize};

use crate::models;

/// UserAgentRequest : Payload to create an agent user
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserAgentRequest {
    #[serde(rename = "name")]
    pub name: String,
}

impl UserAgentRequest {
    /// Payload to create an agent user
    pub fn new(name: String) -> UserAgentRequest {
        UserAgentRequest { name }
    }
}
