/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserAccountLockdownRequest : Payload to trigger account lockdown for a user
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserAccountLockdownRequest {
    /// User to lock. If omitted, locks the current user (self-service).
    #[serde(rename = "user", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user: Option<Option<i32>>,
}

impl UserAccountLockdownRequest {
    /// Payload to trigger account lockdown for a user
    pub fn new() -> UserAccountLockdownRequest {
        UserAccountLockdownRequest {
            user: None,
        }
    }
}

