// authentik
//
// Making authentication simple.
//
// The version of the OpenAPI document: 2026.5.0-rc1
// Contact: hello@goauthentik.io
// Generated by: https://openapi-generator.tech

use serde::{Deserialize, Serialize};

use crate::models;

/// UserPasswordHashSetRequest : Payload to set a user's password from a pre-hashed Django password
/// value.  This only updates authentik's stored password verifier and does not propagate the change
/// to LDAP or Kerberos password-sync integrations.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserPasswordHashSetRequest {
    #[serde(rename = "password_hash")]
    pub password_hash: String,
}

impl UserPasswordHashSetRequest {
    /// Payload to set a user's password from a pre-hashed Django password value.  This only updates
    /// authentik's stored password verifier and does not propagate the change to LDAP or Kerberos
    /// password-sync integrations.
    pub fn new(password_hash: String) -> UserPasswordHashSetRequest {
        UserPasswordHashSetRequest { password_hash }
    }
}
