// authentik
//
// Making authentication simple.
//
// The version of the OpenAPI document: 2026.5.0-rc1
// Contact: hello@goauthentik.io
// Generated by: https://openapi-generator.tech

use serde::{Deserialize, Serialize};

use crate::models;

/// UserAgentAllowedApps : Payload to replace the allowed application list for an agent user
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserAgentAllowedApps {
    /// List of application UUIDs the agent is permitted to access.
    #[serde(rename = "allowed_apps")]
    pub allowed_apps: Vec<uuid::Uuid>,
}

impl UserAgentAllowedApps {
    /// Payload to replace the allowed application list for an agent user
    pub fn new(allowed_apps: Vec<uuid::Uuid>) -> UserAgentAllowedApps {
        UserAgentAllowedApps { allowed_apps }
    }
}
