# Generated by Django 5.2.12 on 2026-04-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_core", "0057_remove_user_groups_remove_user_user_permissions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="meta_hide",
            field=models.BooleanField(
                default=False, help_text="Hide this application from the user dashboard."
            ),
        ),
    ]
